EASY-2846: Add Rule 2.7 on original-filepaths.txt
DANS-KNAW/dans-bagit-profile pull request #24
Opened 2021-09-01 10:34 UTC by lindareijnhoudt

Fixes EASY-2846

# Description of changes
* Add Rule 2.7 on original-filepaths.txt
* Add reference to 2.7.4 to Rule 3.2.4

# How to test

# Related PRs
* [ ] easy-validate-dans-bag

# Notify
@DANS-KNAW/easy

2021-09-01 11:54 UTC, janvanmansum requested changes
Dotted the proverbial i's, see comments. For the rest, looks OK to me.

2021-09-01 11:54 UTC, janvanmansum commented on docs/versions/0.0.0.md
> +1. A DANS bag MAY contain a file `original-filepaths.txt` in the root of the bag
```suggestion
1. A DANS bag MAY contain a file `original-filepaths.txt` in the root of the bag.
```

2021-09-01 11:54 UTC, janvanmansum commented on docs/versions/0.0.0.md
> +2. It MUST be a UTF-8 encoded text file and MUST be formatted as `<physical-bag-relative-path><whitespace><orignal-bag-relative-path>`
```suggestion
2. It MUST be a UTF-8 encoded text file and MUST be formatted as `<physical-bag-relative-path><whitespace><orignal-bag-relative-path>`.
```

2021-09-01 11:54 UTC, janvanmansum commented on docs/versions/0.0.0.md
> +3. `<physical-bag-relative-path>` MUST NOT contain whitespace and MUST correspond one-on-one to an existing payload file
```suggestion
3. `<physical-bag-relative-path>` MUST NOT contain whitespace and MUST correspond one-on-one to an existing payload file.
```

2021-09-01 11:54 UTC, janvanmansum commented on docs/versions/0.0.0.md
> +4.  All `filepath` attributes in the `file` elements in the `files.xml` MUST appear in the `original-filepaths.txt` as an `<orignal-bag-relative-path>`
```suggestion
4.  All `filepath` attributes in the `file` elements in the `files.xml` MUST appear in the `original-filepaths.txt` as an `<orignal-bag-relative-path>`.
```

2021-09-03 10:22 UTC, lindareijnhoudt commented on docs/versions/0.0.0.md
> +   When an `original-filepaths.txt` exists, rule 2.7.4 applies.
```suggestion
   When an `original-filepaths.txt` exists, rule 2.7.2 applies.
```

2021-09-07 07:54 UTC, merged